webpack_encore:
    output_path: '%kernel.project_dir%/public/build'
    builds:
        awesomeTheme: '%kernel.project_dir%/public/build/awesome-theme'
        anotherTheme: '%kernel.project_dir%/public/build/another-theme'
